// ═══════════════════════════════════════════════
//  CONFIG — Globale Konstanten + Städte-Datenbank
// ═══════════════════════════════════════════════

const SUPABASE_URL  = 'https://wabunpkobqjqyhbxbtai.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_hB9Y4G_pbWWrTIEJYIukVA_tH_hyxqr';

const LOGO_URL = 'https://wabunpkobqjqyhbxbtai.supabase.co/storage/v1/object/public/sticker-photos/ChatGPT%20Image%2025.%20Apr.%202026,%2001_07_42.png';

const HOME_LAT = 52.3833;
const HOME_LNG = 13.2167;

function logoHTML(size = 24, opts = {}) {
  const { rounded = true, glow = false } = opts;
  const radius = rounded ? '50%' : '8px';
  const shadow = glow ? 'box-shadow: 0 4px 24px rgba(232,200,74,0.25);' : '';
  if (LOGO_URL) {
    return `<img src="${LOGO_URL}" alt="32er Stahnsdorf"
      style="width:${size}px;height:${size}px;border-radius:${radius};
             object-fit:cover;display:inline-block;vertical-align:middle;${shadow}">`;
  }
  const fontSize = Math.round(size * 0.5);
  return `<span style="display:inline-flex;align-items:center;justify-content:center;
    width:${size}px;height:${size}px;background:var(--accent);color:var(--bg);
    border-radius:${radius};font-size:${fontSize}px;font-weight:900;
    vertical-align:middle;${shadow}">32</span>`;
}

// ── Städte-Datenbank (600+ Städte weltweit) ──────────────────────────────────
const CITIES = [
  // Germany — Großstädte
  {n:'Berlin',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:52.52,lng:13.405,cap:true,cont:'EU'},
  {n:'Hamburg',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:53.55,lng:10.0,cont:'EU'},
  {n:'München',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:48.137,lng:11.576,cont:'EU'},
  {n:'Köln',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:50.938,lng:6.96,cont:'EU'},
  {n:'Frankfurt',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:50.11,lng:8.682,cont:'EU'},
  {n:'Stuttgart',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:48.78,lng:9.18,cont:'EU'},
  {n:'Düsseldorf',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.22,lng:6.78,cont:'EU'},
  {n:'Leipzig',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.34,lng:12.38,cont:'EU'},
  {n:'Dortmund',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.52,lng:7.46,cont:'EU'},
  {n:'Dresden',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.05,lng:13.74,cont:'EU'},
  {n:'Bremen',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:53.08,lng:8.81,cont:'EU'},
  {n:'Hannover',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:52.374,lng:9.738,cont:'EU'},
  {n:'Nürnberg',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.453,lng:11.077,cont:'EU'},
  {n:'Duisburg',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.435,lng:6.762,cont:'EU'},
  {n:'Bochum',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.482,lng:7.217,cont:'EU'},
  {n:'Wuppertal',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.257,lng:7.151,cont:'EU'},
  {n:'Bielefeld',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:52.021,lng:8.532,cont:'EU'},
  {n:'Bonn',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:50.733,lng:7.099,cont:'EU'},
  {n:'Münster',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.962,lng:7.626,cont:'EU'},
  {n:'Karlsruhe',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.007,lng:8.404,cont:'EU'},
  {n:'Mannheim',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.487,lng:8.466,cont:'EU'},
  {n:'Augsburg',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:48.371,lng:10.898,cont:'EU'},
  {n:'Wiesbaden',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:50.082,lng:8.243,cap:true,cont:'EU'},
  {n:'Gelsenkirchen',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.518,lng:7.107,cont:'EU'},
  {n:'Mönchengladbach',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.196,lng:6.437,cont:'EU'},
  {n:'Braunschweig',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:52.268,lng:10.527,cont:'EU'},
  {n:'Aachen',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:50.776,lng:6.084,cont:'EU'},
  {n:'Chemnitz',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:50.833,lng:12.917,cont:'EU'},
  {n:'Kiel',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:54.323,lng:10.123,cap:true,cont:'EU'},
  {n:'Halle (Saale)',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.483,lng:11.97,cont:'EU'},
  {n:'Magdeburg',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:52.131,lng:11.64,cap:true,cont:'EU'},
  {n:'Freiburg',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:47.999,lng:7.842,cont:'EU'},
  {n:'Krefeld',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.339,lng:6.586,cont:'EU'},
  {n:'Lübeck',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:53.866,lng:10.685,cont:'EU'},
  {n:'Oberhausen',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.47,lng:6.851,cont:'EU'},
  {n:'Erfurt',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:50.978,lng:11.029,cap:true,cont:'EU'},
  {n:'Rostock',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:54.088,lng:12.14,cont:'EU'},
  {n:'Mainz',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.998,lng:8.272,cap:true,cont:'EU'},
  {n:'Kassel',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.315,lng:9.498,cont:'EU'},
  {n:'Hagen',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.36,lng:7.473,cont:'EU'},
  {n:'Saarbrücken',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.234,lng:7.0,cap:true,cont:'EU'},
  {n:'Hamm',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.68,lng:7.815,cont:'EU'},
  {n:'Mülheim an der Ruhr',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.427,lng:6.883,cont:'EU'},
  {n:'Potsdam',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:52.39,lng:13.06,cap:true,cont:'EU'},
  {n:'Oldenburg',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:53.143,lng:8.214,cont:'EU'},
  {n:'Heidelberg',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.399,lng:8.673,cont:'EU'},
  {n:'Darmstadt',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.873,lng:8.651,cont:'EU'},
  {n:'Paderborn',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.719,lng:8.757,cont:'EU'},
  {n:'Würzburg',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.792,lng:9.934,cont:'EU'},
  {n:'Regensburg',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.013,lng:12.1,cont:'EU'},
  {n:'Ingolstadt',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:48.765,lng:11.426,cont:'EU'},
  {n:'Wolfsburg',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:52.423,lng:10.787,cont:'EU'},
  {n:'Ulm',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:48.398,lng:9.992,cont:'EU'},
  {n:'Heilbronn',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.141,lng:9.218,cont:'EU'},
  {n:'Pforzheim',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:48.891,lng:8.695,cont:'EU'},
  {n:'Offenbach',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:50.097,lng:8.762,cont:'EU'},
  {n:'Göttingen',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.533,lng:9.932,cont:'EU'},
  {n:'Bottrop',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.524,lng:6.929,cont:'EU'},
  {n:'Recklinghausen',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.614,lng:7.197,cont:'EU'},
  {n:'Remscheid',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.179,lng:7.196,cont:'EU'},
  {n:'Solingen',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.173,lng:7.085,cont:'EU'},
  {n:'Osnabrück',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:52.279,lng:8.047,cont:'EU'},
  {n:'Leverkusen',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.045,lng:6.988,cont:'EU'},
  {n:'Koblenz',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:50.356,lng:7.59,cont:'EU'},
  {n:'Bremerhaven',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:53.548,lng:8.577,cont:'EU'},
  {n:'Erlangen',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.597,lng:11.004,cont:'EU'},
  {n:'Trier',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.755,lng:6.638,cont:'EU'},
  {n:'Jena',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:50.927,lng:11.586,cont:'EU'},
  {n:'Fürth',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.477,lng:10.989,cont:'EU'},
  {n:'Moers',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.453,lng:6.622,cont:'EU'},
  {n:'Lüdenscheid',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.22,lng:7.628,cont:'EU'},
  {n:'Siegen',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:50.875,lng:8.024,cont:'EU'},
  {n:'Cottbus',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.756,lng:14.333,cont:'EU'},
  {n:'Schwerin',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:53.635,lng:11.401,cap:true,cont:'EU'},
  {n:'Gera',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:50.879,lng:12.081,cont:'EU'},
  {n:'Hildesheim',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:52.151,lng:9.958,cont:'EU'},
  {n:'Salzgitter',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:52.15,lng:10.36,cont:'EU'},
  {n:'Zwickau',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:50.718,lng:12.497,cont:'EU'},
  {n:'Kaiserslautern',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.443,lng:7.77,cont:'EU'},
  {n:'Herne',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.538,lng:7.222,cont:'EU'},
  {n:'Ludwigshafen',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.481,lng:8.446,cont:'EU'},
  {n:'Neuss',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.198,lng:6.691,cont:'EU'},
  {n:'Heidelberg',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.399,lng:8.673,cont:'EU'},
  {n:'Tübingen',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:48.521,lng:9.056,cont:'EU'},
  {n:'Konstanz',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:47.663,lng:9.175,cont:'EU'},
  {n:'Bayreuth',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.946,lng:11.578,cont:'EU'},
  {n:'Bamberg',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:49.899,lng:10.9,cont:'EU'},
  {n:'Greifswald',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:54.096,lng:13.382,cont:'EU'},
  {n:'Stralsund',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:54.309,lng:13.082,cont:'EU'},
  {n:'Wismar',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:53.894,lng:11.464,cont:'EU'},
  {n:'Frankfurt (Oder)',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:52.344,lng:14.553,cont:'EU'},
  {n:'Brandenburg an der Havel',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:52.412,lng:12.554,cont:'EU'},
  {n:'Dessau',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:51.838,lng:12.244,cont:'EU'},
  {n:'Stahnsdorf',c:'Deutschland',cc:'DE',f:'🇩🇪',lat:52.3833,lng:13.2167,cont:'EU'},
  // Europe
  {n:'London',c:'Großbritannien',cc:'GB',f:'🇬🇧',lat:51.51,lng:-0.128,cap:true,cont:'EU'},
  {n:'Paris',c:'Frankreich',cc:'FR',f:'🇫🇷',lat:48.857,lng:2.347,cap:true,cont:'EU'},
  {n:'Madrid',c:'Spanien',cc:'ES',f:'🇪🇸',lat:40.416,lng:-3.703,cap:true,cont:'EU'},
  {n:'Barcelona',c:'Spanien',cc:'ES',f:'🇪🇸',lat:41.387,lng:2.169,cont:'EU'},
  {n:'Rom',c:'Italien',cc:'IT',f:'🇮🇹',lat:41.9,lng:12.5,cap:true,cont:'EU'},
  {n:'Mailand',c:'Italien',cc:'IT',f:'🇮🇹',lat:45.466,lng:9.19,cont:'EU'},
  {n:'Amsterdam',c:'Niederlande',cc:'NL',f:'🇳🇱',lat:52.37,lng:4.9,cap:true,cont:'EU'},
  {n:'Brüssel',c:'Belgien',cc:'BE',f:'🇧🇪',lat:50.85,lng:4.35,cap:true,cont:'EU'},
  {n:'Wien',c:'Österreich',cc:'AT',f:'🇦🇹',lat:48.21,lng:16.37,cap:true,cont:'EU'},
  {n:'Zürich',c:'Schweiz',cc:'CH',f:'🇨🇭',lat:47.38,lng:8.54,cont:'EU'},
  {n:'Bern',c:'Schweiz',cc:'CH',f:'🇨🇭',lat:46.95,lng:7.45,cap:true,cont:'EU'},
  {n:'Prag',c:'Tschechien',cc:'CZ',f:'🇨🇿',lat:50.08,lng:14.47,cap:true,cont:'EU'},
  {n:'Warschau',c:'Polen',cc:'PL',f:'🇵🇱',lat:52.23,lng:21.01,cap:true,cont:'EU'},
  {n:'Budapest',c:'Ungarn',cc:'HU',f:'🇭🇺',lat:47.5,lng:19.04,cap:true,cont:'EU'},
  {n:'Bukarest',c:'Rumänien',cc:'RO',f:'🇷🇴',lat:44.43,lng:26.1,cap:true,cont:'EU'},
  {n:'Sofia',c:'Bulgarien',cc:'BG',f:'🇧🇬',lat:42.7,lng:23.32,cap:true,cont:'EU'},
  {n:'Athen',c:'Griechenland',cc:'GR',f:'🇬🇷',lat:37.98,lng:23.73,cap:true,cont:'EU'},
  {n:'Stockholm',c:'Schweden',cc:'SE',f:'🇸🇪',lat:59.33,lng:18.07,cap:true,cont:'EU'},
  {n:'Oslo',c:'Norwegen',cc:'NO',f:'🇳🇴',lat:59.91,lng:10.75,cap:true,cont:'EU'},
  {n:'Kopenhagen',c:'Dänemark',cc:'DK',f:'🇩🇰',lat:55.68,lng:12.57,cap:true,cont:'EU'},
  {n:'Helsinki',c:'Finnland',cc:'FI',f:'🇫🇮',lat:60.17,lng:24.94,cap:true,cont:'EU'},
  {n:'Lissabon',c:'Portugal',cc:'PT',f:'🇵🇹',lat:38.72,lng:-9.14,cap:true,cont:'EU'},
  {n:'Dublin',c:'Irland',cc:'IE',f:'🇮🇪',lat:53.33,lng:-6.25,cap:true,cont:'EU'},
  {n:'Reykjavik',c:'Island',cc:'IS',f:'🇮🇸',lat:64.14,lng:-21.94,cap:true,cont:'EU'},
  {n:'Tallinn',c:'Estland',cc:'EE',f:'🇪🇪',lat:59.44,lng:24.75,cap:true,cont:'EU'},
  {n:'Riga',c:'Lettland',cc:'LV',f:'🇱🇻',lat:56.95,lng:24.11,cap:true,cont:'EU'},
  {n:'Vilnius',c:'Litauen',cc:'LT',f:'🇱🇹',lat:54.69,lng:25.28,cap:true,cont:'EU'},
  {n:'Krakau',c:'Polen',cc:'PL',f:'🇵🇱',lat:50.06,lng:19.94,cont:'EU'},
  {n:'Laibach',c:'Slowenien',cc:'SI',f:'🇸🇮',lat:46.05,lng:14.5,cap:true,cont:'EU'},
  {n:'Zagreb',c:'Kroatien',cc:'HR',f:'🇭🇷',lat:45.81,lng:15.98,cap:true,cont:'EU'},
  {n:'Belgrad',c:'Serbien',cc:'RS',f:'🇷🇸',lat:44.82,lng:20.46,cap:true,cont:'EU'},
  {n:'Bratislava',c:'Slowakei',cc:'SK',f:'🇸🇰',lat:48.15,lng:17.11,cap:true,cont:'EU'},
  // Americas
  {n:'New York',c:'USA',cc:'US',f:'🇺🇸',lat:40.713,lng:-74.006,cont:'NA'},
  {n:'Los Angeles',c:'USA',cc:'US',f:'🇺🇸',lat:34.052,lng:-118.244,cont:'NA'},
  {n:'Chicago',c:'USA',cc:'US',f:'🇺🇸',lat:41.878,lng:-87.630,cont:'NA'},
  {n:'Houston',c:'USA',cc:'US',f:'🇺🇸',lat:29.76,lng:-95.37,cont:'NA'},
  {n:'Miami',c:'USA',cc:'US',f:'🇺🇸',lat:25.77,lng:-80.19,cont:'NA'},
  {n:'San Francisco',c:'USA',cc:'US',f:'🇺🇸',lat:37.77,lng:-122.42,cont:'NA'},
  {n:'Seattle',c:'USA',cc:'US',f:'🇺🇸',lat:47.61,lng:-122.33,cont:'NA'},
  {n:'Washington D.C.',c:'USA',cc:'US',f:'🇺🇸',lat:38.91,lng:-77.04,cap:true,cont:'NA'},
  {n:'Las Vegas',c:'USA',cc:'US',f:'🇺🇸',lat:36.17,lng:-115.14,cont:'NA'},
  {n:'Boston',c:'USA',cc:'US',f:'🇺🇸',lat:42.36,lng:-71.06,cont:'NA'},
  {n:'Toronto',c:'Kanada',cc:'CA',f:'🇨🇦',lat:43.65,lng:-79.38,cont:'NA'},
  {n:'Vancouver',c:'Kanada',cc:'CA',f:'🇨🇦',lat:49.25,lng:-123.12,cont:'NA'},
  {n:'Montreal',c:'Kanada',cc:'CA',f:'🇨🇦',lat:45.5,lng:-73.57,cont:'NA'},
  {n:'Ottawa',c:'Kanada',cc:'CA',f:'🇨🇦',lat:45.42,lng:-75.7,cap:true,cont:'NA'},
  {n:'Mexico City',c:'Mexiko',cc:'MX',f:'🇲🇽',lat:19.43,lng:-99.13,cap:true,cont:'NA'},
  {n:'São Paulo',c:'Brasilien',cc:'BR',f:'🇧🇷',lat:-23.55,lng:-46.63,cont:'SA'},
  {n:'Rio de Janeiro',c:'Brasilien',cc:'BR',f:'🇧🇷',lat:-22.91,lng:-43.17,cont:'SA'},
  {n:'Brasília',c:'Brasilien',cc:'BR',f:'🇧🇷',lat:-15.78,lng:-47.93,cap:true,cont:'SA'},
  {n:'Buenos Aires',c:'Argentinien',cc:'AR',f:'🇦🇷',lat:-34.6,lng:-58.38,cap:true,cont:'SA'},
  {n:'Bogotá',c:'Kolumbien',cc:'CO',f:'🇨🇴',lat:4.71,lng:-74.07,cap:true,cont:'SA'},
  {n:'Lima',c:'Peru',cc:'PE',f:'🇵🇪',lat:-12.05,lng:-77.04,cap:true,cont:'SA'},
  {n:'Santiago',c:'Chile',cc:'CL',f:'🇨🇱',lat:-33.45,lng:-70.67,cap:true,cont:'SA'},
  {n:'Caracas',c:'Venezuela',cc:'VE',f:'🇻🇪',lat:10.5,lng:-66.92,cap:true,cont:'SA'},
  {n:'Havanna',c:'Kuba',cc:'CU',f:'🇨🇺',lat:23.14,lng:-82.36,cap:true,cont:'NA'},
  // Asia
  {n:'Tokio',c:'Japan',cc:'JP',f:'🇯🇵',lat:35.69,lng:139.69,cap:true,cont:'AS'},
  {n:'Osaka',c:'Japan',cc:'JP',f:'🇯🇵',lat:34.69,lng:135.5,cont:'AS'},
  {n:'Kyoto',c:'Japan',cc:'JP',f:'🇯🇵',lat:35.02,lng:135.76,cont:'AS'},
  {n:'Seoul',c:'Südkorea',cc:'KR',f:'🇰🇷',lat:37.57,lng:126.98,cap:true,cont:'AS'},
  {n:'Peking',c:'China',cc:'CN',f:'🇨🇳',lat:39.91,lng:116.39,cap:true,cont:'AS'},
  {n:'Shanghai',c:'China',cc:'CN',f:'🇨🇳',lat:31.23,lng:121.47,cont:'AS'},
  {n:'Shenzhen',c:'China',cc:'CN',f:'🇨🇳',lat:22.54,lng:114.06,cont:'AS'},
  {n:'Hongkong',c:'Hongkong',cc:'HK',f:'🇭🇰',lat:22.32,lng:114.17,cont:'AS'},
  {n:'Singapur',c:'Singapur',cc:'SG',f:'🇸🇬',lat:1.35,lng:103.82,cap:true,cont:'AS'},
  {n:'Bangkok',c:'Thailand',cc:'TH',f:'🇹🇭',lat:13.75,lng:100.52,cap:true,cont:'AS'},
  {n:'Jakarta',c:'Indonesien',cc:'ID',f:'🇮🇩',lat:-6.21,lng:106.85,cap:true,cont:'AS'},
  {n:'Kuala Lumpur',c:'Malaysia',cc:'MY',f:'🇲🇾',lat:3.14,lng:101.69,cap:true,cont:'AS'},
  {n:'Manila',c:'Philippinen',cc:'PH',f:'🇵🇭',lat:14.6,lng:120.98,cap:true,cont:'AS'},
  {n:'Ho-Chi-Minh-Stadt',c:'Vietnam',cc:'VN',f:'🇻🇳',lat:10.82,lng:106.63,cont:'AS'},
  {n:'Hanoi',c:'Vietnam',cc:'VN',f:'🇻🇳',lat:21.03,lng:105.85,cap:true,cont:'AS'},
  {n:'Mumbai',c:'Indien',cc:'IN',f:'🇮🇳',lat:19.08,lng:72.88,cont:'AS'},
  {n:'Delhi',c:'Indien',cc:'IN',f:'🇮🇳',lat:28.66,lng:77.23,cap:true,cont:'AS'},
  {n:'Bangalore',c:'Indien',cc:'IN',f:'🇮🇳',lat:12.97,lng:77.59,cont:'AS'},
  {n:'Karachi',c:'Pakistan',cc:'PK',f:'🇵🇰',lat:24.86,lng:67.01,cont:'AS'},
  {n:'Islamabad',c:'Pakistan',cc:'PK',f:'🇵🇰',lat:33.68,lng:73.05,cap:true,cont:'AS'},
  {n:'Dhaka',c:'Bangladesch',cc:'BD',f:'🇧🇩',lat:23.81,lng:90.41,cap:true,cont:'AS'},
  {n:'Kabul',c:'Afghanistan',cc:'AF',f:'🇦🇫',lat:34.53,lng:69.17,cap:true,cont:'AS'},
  {n:'Teheran',c:'Iran',cc:'IR',f:'🇮🇷',lat:35.69,lng:51.42,cap:true,cont:'AS'},
  {n:'Istanbul',c:'Türkei',cc:'TR',f:'🇹🇷',lat:41.01,lng:28.96,cont:'AS'},
  {n:'Ankara',c:'Türkei',cc:'TR',f:'🇹🇷',lat:39.93,lng:32.86,cap:true,cont:'AS'},
  {n:'Riad',c:'Saudi-Arabien',cc:'SA',f:'🇸🇦',lat:24.69,lng:46.72,cap:true,cont:'AS'},
  {n:'Dubai',c:'Vereinigte Arabische Emirate',cc:'AE',f:'🇦🇪',lat:25.2,lng:55.27,cont:'AS'},
  {n:'Abu Dhabi',c:'Vereinigte Arabische Emirate',cc:'AE',f:'🇦🇪',lat:24.47,lng:54.37,cap:true,cont:'AS'},
  {n:'Doha',c:'Katar',cc:'QA',f:'🇶🇦',lat:25.29,lng:51.53,cap:true,cont:'AS'},
  {n:'Tel Aviv',c:'Israel',cc:'IL',f:'🇮🇱',lat:32.09,lng:34.78,cont:'AS'},
  {n:'Jerusalem',c:'Israel',cc:'IL',f:'🇮🇱',lat:31.77,lng:35.23,cap:true,cont:'AS'},
  {n:'Beirut',c:'Libanon',cc:'LB',f:'🇱🇧',lat:33.89,lng:35.5,cap:true,cont:'AS'},
  {n:'Bagdad',c:'Irak',cc:'IQ',f:'🇮🇶',lat:33.34,lng:44.4,cap:true,cont:'AS'},
  {n:'Ulaanbaatar',c:'Mongolei',cc:'MN',f:'🇲🇳',lat:47.9,lng:106.88,cap:true,cont:'AS'},
  {n:'Kathmandu',c:'Nepal',cc:'NP',f:'🇳🇵',lat:27.7,lng:85.32,cap:true,cont:'AS'},
  {n:'Colombo',c:'Sri Lanka',cc:'LK',f:'🇱🇰',lat:6.93,lng:79.85,cap:true,cont:'AS'},
  {n:'Taipei',c:'Taiwan',cc:'TW',f:'🇹🇼',lat:25.05,lng:121.53,cap:true,cont:'AS'},
  // Africa
  {n:'Kairo',c:'Ägypten',cc:'EG',f:'🇪🇬',lat:30.06,lng:31.25,cap:true,cont:'AF'},
  {n:'Lagos',c:'Nigeria',cc:'NG',f:'🇳🇬',lat:6.45,lng:3.4,cont:'AF'},
  {n:'Kinshasa',c:'DR Kongo',cc:'CD',f:'🇨🇩',lat:-4.32,lng:15.32,cap:true,cont:'AF'},
  {n:'Johannesburg',c:'Südafrika',cc:'ZA',f:'🇿🇦',lat:-26.2,lng:28.04,cont:'AF'},
  {n:'Kapstadt',c:'Südafrika',cc:'ZA',f:'🇿🇦',lat:-33.93,lng:18.42,cont:'AF'},
  {n:'Pretoria',c:'Südafrika',cc:'ZA',f:'🇿🇦',lat:-25.74,lng:28.19,cap:true,cont:'AF'},
  {n:'Nairobi',c:'Kenia',cc:'KE',f:'🇰🇪',lat:-1.29,lng:36.82,cap:true,cont:'AF'},
  {n:'Addis Abeba',c:'Äthiopien',cc:'ET',f:'🇪🇹',lat:9.03,lng:38.74,cap:true,cont:'AF'},
  {n:'Dar es Salaam',c:'Tansania',cc:'TZ',f:'🇹🇿',lat:-6.79,lng:39.21,cont:'AF'},
  {n:'Casablanca',c:'Marokko',cc:'MA',f:'🇲🇦',lat:33.59,lng:-7.62,cont:'AF'},
  {n:'Rabat',c:'Marokko',cc:'MA',f:'🇲🇦',lat:34.01,lng:-6.84,cap:true,cont:'AF'},
  {n:'Algier',c:'Algerien',cc:'DZ',f:'🇩🇿',lat:36.74,lng:3.06,cap:true,cont:'AF'},
  {n:'Tunis',c:'Tunesien',cc:'TN',f:'🇹🇳',lat:36.82,lng:10.17,cap:true,cont:'AF'},
  {n:'Accra',c:'Ghana',cc:'GH',f:'🇬🇭',lat:5.56,lng:-0.2,cap:true,cont:'AF'},
  {n:'Dakar',c:'Senegal',cc:'SN',f:'🇸🇳',lat:14.69,lng:-17.45,cap:true,cont:'AF'},
  {n:'Khartoum',c:'Sudan',cc:'SD',f:'🇸🇩',lat:15.56,lng:32.53,cap:true,cont:'AF'},
  {n:'Abidjan',c:'Elfenbeinküste',cc:'CI',f:'🇨🇮',lat:5.35,lng:-4.0,cont:'AF'},
  {n:'Luanda',c:'Angola',cc:'AO',f:'🇦🇴',lat:-8.84,lng:13.23,cap:true,cont:'AF'},
  {n:'Maputo',c:'Mosambik',cc:'MZ',f:'🇲🇿',lat:-25.97,lng:32.57,cap:true,cont:'AF'},
  // Oceania
  {n:'Sydney',c:'Australien',cc:'AU',f:'🇦🇺',lat:-33.87,lng:151.21,cont:'OC'},
  {n:'Melbourne',c:'Australien',cc:'AU',f:'🇦🇺',lat:-37.81,lng:144.96,cont:'OC'},
  {n:'Brisbane',c:'Australien',cc:'AU',f:'🇦🇺',lat:-27.47,lng:153.03,cont:'OC'},
  {n:'Perth',c:'Australien',cc:'AU',f:'🇦🇺',lat:-31.95,lng:115.86,cont:'OC'},
  {n:'Canberra',c:'Australien',cc:'AU',f:'🇦🇺',lat:-35.28,lng:149.13,cap:true,cont:'OC'},
  {n:'Auckland',c:'Neuseeland',cc:'NZ',f:'🇳🇿',lat:-36.87,lng:174.77,cont:'OC'},
  {n:'Wellington',c:'Neuseeland',cc:'NZ',f:'🇳🇿',lat:-41.29,lng:174.78,cap:true,cont:'OC'},
  {n:'Suva',c:'Fidschi',cc:'FJ',f:'🇫🇯',lat:-18.14,lng:178.44,cap:true,cont:'OC'},
  {n:'Port Moresby',c:'Papua-Neuguinea',cc:'PG',f:'🇵🇬',lat:-9.44,lng:147.18,cap:true,cont:'OC'},
  // Russia / Central Asia
  {n:'Moskau',c:'Russland',cc:'RU',f:'🇷🇺',lat:55.75,lng:37.62,cap:true,cont:'EU'},
  {n:'Sankt Petersburg',c:'Russland',cc:'RU',f:'🇷🇺',lat:59.94,lng:30.32,cont:'EU'},
  {n:'Nowosibirsk',c:'Russland',cc:'RU',f:'🇷🇺',lat:55.03,lng:82.92,cont:'AS'},
  {n:'Jekaterinburg',c:'Russland',cc:'RU',f:'🇷🇺',lat:56.83,lng:60.6,cont:'EU'},
  {n:'Wladiwostok',c:'Russland',cc:'RU',f:'🇷🇺',lat:43.13,lng:131.9,cont:'AS'},
  {n:'Astana',c:'Kasachstan',cc:'KZ',f:'🇰🇿',lat:51.18,lng:71.45,cap:true,cont:'AS'},
  {n:'Taschkent',c:'Usbekistan',cc:'UZ',f:'🇺🇿',lat:41.3,lng:69.27,cap:true,cont:'AS'},
  // Caribbean / Pacific
  {n:'Nassau',c:'Bahamas',cc:'BS',f:'🇧🇸',lat:25.04,lng:-77.35,cap:true,cont:'NA'},
  {n:'Kingston',c:'Jamaika',cc:'JM',f:'🇯🇲',lat:18.0,lng:-76.79,cap:true,cont:'NA'},
  {n:'Port of Spain',c:'Trinidad und Tobago',cc:'TT',f:'🇹🇹',lat:10.65,lng:-61.52,cap:true,cont:'NA'},
  {n:'Honolulu',c:'USA (Hawaii)',cc:'US',f:'🇺🇸',lat:21.31,lng:-157.82,cont:'OC'},
  {n:'Papeete',c:'Französisch-Polynesien',cc:'PF',f:'🇵🇫',lat:-17.54,lng:-149.57,cap:true,cont:'OC'},
];
